config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', { to: 'welcome#index', as: 'root' })
  get('/contact/new', { to: 'contact#new' })
  post('/contact', {to: 'contact#create'})

  resources :questions do
    resources :answers, only:[:create, :destroy], shallow: true
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  # Active Record is known as an ORM, an Object Relational Mapper
  # We use objects to represent tables and data from our database.
  # This class "Question" represents the "questions" table.
  # Instances of the Question class represent a row of data in 
  # the "questions" table.

  # We generated this file when we ran the following command. 
  # Make sure that model is singular.
  # rails g model question title body:text

  # To read more on validations: https://guides.rubyonrails.org/active_record_validations.html
  validates(:title, presence: true, uniqueness: true)

  # To read an array of error messages after failling validation:
  # record.errors.full_messages
  validates(
    :body, 
    presence: { message: "must include a question" },
    length: { minimum: 10 },
  )

  #validates(:view_count, numericality: { greater_than_or_equal_to: 0 })

  # Custom validations
  # Use the "validate" (singluar) for custom validations
  validate(:no_monkey)
  validate(:no_title_in_body)

  # Create a scope with a class method. We can create a scope with
  # the "scope" method. The arguments are:
  # 1. The class method's name as a symbol
  # 2. A lambda. The return value is returned from the class method.
  scope(:recent_ten, ->{ order(created_at: :desc).limit(10) })
  # The above is equivalent to:
  # def self.recent_ten
  #   order(created_at: :desc).limit(10)
  # end

  scope(:search, ->(word){ where('title ILIKE ? OR body ILIKE ?', "%#{word}%", "%#{word}%") })
  # There exists many callbacks that run a code block at different 
  # stages of a record's lifecycle. List of callbacks found here:
  # https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks
  before_save do 
    # self is the record/instance
    # Immediately before saving to the database, captialize the title
    self.title = title.capitalize 
  end

  private

  def no_monkey
    # For each column/attribute, the attr_accessors are already defined
    # We can access each attribute for each instance e.g. "body", "title"

    # &. is a safe navigation operator. It's used like the "." to 
    # call methods on an object. If the method does not exist for 
    # the object, "nil" will be returned instead of raising an error.
    # Similar body && body.downcase
    if body&.downcase.include?("monkey")
      # To make a record invalid, add a validation error using the 
      # "add" method on the error object of the instance.
      # Its arguments are:
      # 1. Name of the invalid column as a symbol
      # 2. Error message as a string
      errors.add(:body, "must not include monkeys")
    end
  end

  def no_title_in_body
    if body&.downcase.include?(title.downcase)
      errors.add(:body, "must not include the title")
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_question, only: [:edit, :update, :show, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]
  def new
    @question = Question.new
  end
  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save 
      flash[:primary] = "#{@question.title} created"
      redirect_to question_path(@question.id)
    else
      render :new
    end
  end
  def show
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :desc)
  end
  def index
    @questions = Question.all
  end
  def edit
  end
  def update
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end
  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
  def find_question
    @question = Question.find(params[:id])
  end

  def authorize 
    unless can?(:edit, @question)
      flash[:primary] = "Not authorized"
      redirect_to root_path
    end
  end
end

app/views/questions/_form.html.erb
<%#
  To create a form for resource (i.e. a model), use the 
  form_with helper instead of the form_tag. Its argumments are:
  1. A named argument "model" which is assigned an instance of 
    the model. This question instance will be a new question
    from the new action. form_with checks to see if the instance
    of the question is persisted. If it is, upon submission of 
    this form a PATCH request is made, otherwise it makes a POST
  2. A named argument "local". We set this to true so that it
    doesn't submit the form using AJAX.
%>
<%= form_with(model: @question, local: true) do |form| %>
  <% if @question.errors.present? %>
    <p>
      <%= @question.errors.full_messages.join(", ") %>
    </p>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question Form</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to question.title, question_path(question) %>
    </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>New Question Form</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>

<p>
  Viewed <%= pluralize(@question.view_count, 'time') %>
</p>
<p>
  Asked <%= time_ago_in_words(@question.created_at) %> ago by <%= @question.user&.full_name || "[deleted]" %>
</p>
<p>
  Last edited <%= time_ago_in_words(@question.updated_at) %> ago
</p>
<% if can?(:edit, @question) %>
<div>
  <%= link_to 'Edit', edit_question_path(@question) %>
  |
  <%# 
    Regular HTML links can only make GET requests. "link_to"
    allows us to use other verbs such as DELETE. We pass a named
    argument called "method" with the symbol of the HTTP verb as
    an argument. If you confirm with the dialog then it will 
    make the request.
  %>
  <%= link_to(
      'Delete', 
      question_path(@question),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this question?"}
    ) 
  %>
</div>
<% end %>

<h2><%= @answers.count %> Answers</h2>

<%# 
  When two instances are added to model, it will generate a nested 
  resource route e.g. question_answers_path(@question). If the @answer 
  is not peristed, request will be a POST, and if it is then it will be a PATCH. 
%>
<%= form_with model: [@question, @answer], local: true do |form| %>
  <% if @answer.errors.present? %>
    <p>
      <%= answers.errors.full_messages.join(", ") %>
    </p>
  <% end %>
  <div>
    <%= form.text_area(
      :body,
      cols: 50,
      rows: 5,
      placeholder: "Provide an answer..."
    ) %>
  </div>
  <%= form.submit "Answer" %>
<% end %>

<ul>
  <% @answers.each do |answer| %>
    <li>
      <p>
        <%= answer.body %> <br>
        <% if can?(:crud, answer) %>
        <small>
        <%= link_to(
          'Delete', 
          answer_path(answer),
          method: :delete,
          data: { confirm: "Are you sure?" }
        ) %>
        </small>
        -
        <% end %>
        <small>
          Answered <%= time_ago_in_words(answer.created_at) %> ago by <%= answer.user&.full_name || "[deleted]" %>
        </small>
      </p>
    </li>
  <% end %>
</ul>